services:
  #api-gate:
  #  build: api-gate/
  #  ports:
  #    - 8080:8080
  #  depends_on:
  #    - auth-ms
  #    - some-ms

  auth-ms:
    build: auth-ms/
    depends_on:
      - db
    restart: always

  some-ms:
    build: some-ms/
    depends_on:
      - db
    restart: always

  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=pass1234
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
